<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\ECommerce.Domain\ECommerce.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="15.1.0" />
      <PackageReference Include="FluentValidation" Version="12.1.1" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Configuration\" />
    </ItemGroup>

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <RootNamespace>ECommerce.Application</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

</Project>
