// <auto-generated />
using E_Commerece.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_Commerece.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E_Commerece.Core.Entites.Product.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Devices, gadgets, and electronic accessories",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Men’s, women’s, and children’s fashion items",
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Appliances, furniture, and home improvement tools",
                            Name = "Home & Kitchen"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Cosmetics, skincare, and healthcare products",
                            Name = "Beauty & Health"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Educational, fiction, and non-fiction books",
                            Name = "Books"
                        });
                });

            modelBuilder.Entity("E_Commerece.Core.Entites.Product.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Photos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageName = "Iphone1.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageName = "Iphone2.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 3,
                            ImageName = "Iphone3.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 4,
                            ImageName = "Iphone4.jpg",
                            ProductId = 1
                        });
                });

            modelBuilder.Entity("E_Commerece.Core.Entites.Product.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Apple smartphone with A17 chip and dual camera system.",
                            Name = "iPhone 15",
                            Price = 1199.99m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Stylish blue denim jacket for men.",
                            Name = "Men’s Denim Jacket",
                            Price = 89.5m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "Compact kitchen microwave with digital controls.",
                            Name = "Microwave Oven",
                            Price = 230m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Description = "Gentle foaming face wash suitable for all skin types.",
                            Name = "Facial Cleanser",
                            Price = 15.75m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            Description = "Comprehensive book on C# and .NET development.",
                            Name = "C# Programming Guide",
                            Price = 39.99m
                        });
                });

            modelBuilder.Entity("E_Commerece.Core.Entites.Product.Photo", b =>
                {
                    b.HasOne("E_Commerece.Core.Entites.Product.Product", null)
                        .WithMany("Photos")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("E_Commerece.Core.Entites.Product.Product", b =>
                {
                    b.HasOne("E_Commerece.Core.Entites.Product.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("E_Commerece.Core.Entites.Product.Product", b =>
                {
                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
